services:
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "29092:29092"
    environment:
      # KRaft mode
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # Listeners
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      # Single-broker internal topics
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS: 1

      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_NUM_PARTITIONS: 1

      # Local development
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  console:
    image: docker.redpanda.com/redpandadata/console:latest
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "18080:8080"
    environment:
      KAFKA_BROKERS: "kafka:9092"

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "4318:4318"   # OTLP HTTP

  init-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint:
      - /bin/bash
      - -lc
      - |
        set -euo pipefail

        TOPICS=(
          "sample-topic"
          "sample-tx-topic"
          "sample-share-topic"
          "sample-eos-input-topic"
          "sample-eos-output-topic"
          "sample-otel-topic-a"
          "sample-otel-topic-b"
        )

        for topic in "$${TOPICS[@]}"; do
          echo "Creating topic: $${topic}"

          kafka-topics \
            --bootstrap-server kafka:9092 \
            --create \
            --if-not-exists \
            --topic "$${topic}" \
            --replication-factor 1 \
            --partitions 3
        done

        echo "Kafka topics:"
        kafka-topics --bootstrap-server kafka:9092 --list